version: 2

project_name: intent

before:
  hooks:
    - go mod tidy

builds:
  - id: intent
    main: ./cmd/intent
    env: [CGO_ENABLED=0]
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/intentregistry/intent-cli/internal/version.Version={{.Version}}
      - -X github.com/intentregistry/intent-cli/internal/version.Commit={{.Commit}}
      - -X github.com/intentregistry/intent-cli/internal/version.Date={{.Date}}

archives:
  - id: tarballs
    builds: [intent]
    format: tar.gz
    # Results: intent-darwin-amd64.tar.gz, intent-darwin-arm64.tar.gz, etc.
    name_template: "intent-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

# Homebrew tap automation (we wire token in the CI job below)
brews:
  - name: intent-cli
    repository:
      owner: intentregistry
      name: homebrew-tap
    description: "IntentRegistry CLI — publish and install AI Intents"
    homepage: "https://intentregistry.com"
    license: "MIT"
    commit_author:
      name: "Intent Bot"
      email: "bot@intentregistry.com"
    install: |
      bin.install "intent"
    test: |
      system "#{bin}/intent", "--version"

changelog:
  use: github